## Import Required Libraries

In [41]:
pip install xgboost


Note: you may need to restart the kernel to use updated packages.


In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC,LinearSVC
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier, plot_tree
from xgboost import XGBClassifier
from ucimlrepo import fetch_ucirepo
import warnings
warnings.filterwarnings('ignore')

---
# PART 1: BINARY CLASSIFICATION WITH SVM
---

## Load the Sonar Dataset from UCI Repository

In [43]:
from ucimlrepo import fetch_ucirepo
print("Loading Sonar dataset...")
sonar = fetch_ucirepo(id=151)
X = sonar.data.features
X_sonar = X.to_numpy()
print(X_sonar)
y = sonar.data.targets
y_sonar=y.to_numpy()
print(y_sonar)

Loading Sonar dataset...
[[0.02   0.0371 0.0428 ... 0.0084 0.009  0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
[['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['

## Encode the Target Labels using LabelEncoder()

In [44]:
from sklearn.preprocessing import LabelEncoder
# Suppose you already have X and y
# e.g., y = df['target']
le = LabelEncoder()
y_sonar2 = le.fit_transform(y_sonar)
y_sonar2 = np.where(y_sonar2 == 0, -1, 1)
print(y_sonar2)

[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


## Split the Data into 80% Training and 20% Testing Sets

In [45]:
X_train_sonar, X_test_sonar, y_train_sonar, y_test_sonar = train_test_split(X_sonar, y_sonar2, train_size=0.8, test_size=0.2,random_state=42, stratify=y)

---
## 1.1. Linear Kernel SVM without Hyperparameter Tuning
---

## Create a Pipeline with StandardScaler and Linear SVM

In [46]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),        
    ('svm', LinearSVC(C=5.0, random_state=42))]) #normalize features and create a support vector machine 

## Train the Linear SVM Model

In [47]:
pipeline.fit(X_train_sonar, y_train_sonar)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm', LinearSVC(C=5.0, random_state=42))])

## Predict on the Test Set and Calculate Accuracies and Print it

In [48]:
y_pred=pipeline.predict(X_test_sonar)

In [49]:
def accuracy(y_pred,y_test):
 accuracy = np.mean(y_pred == y_test)
 return accuracy
acc=accuracy(y_pred,y_test_sonar)
print(f"Model Accuracy: {acc:.3f}")

Model Accuracy: 0.810


## Display Classification Report for Linear SVM

In [50]:
print("\nClassification Report:\n", classification_report(y_test_sonar, y_pred, target_names=["Mine", "Rock"]))


Classification Report:
               precision    recall  f1-score   support

        Mine       0.77      0.91      0.83        22
        Rock       0.88      0.70      0.78        20

    accuracy                           0.81        42
   macro avg       0.82      0.80      0.81        42
weighted avg       0.82      0.81      0.81        42



## Display Confusion Matrix for Linear SVM

In [51]:
 confusion=confusion_matrix(y_test_sonar,y_pred)
print(confusion)

[[20  2]
 [ 6 14]]


---
## 1.2. SVM with GridSearchCV and 5-Fold Cross-Validation
---

## Create a Pipeline for GridSearchCV

In [52]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

## Define the Parameter Grid for Different Kernels

In [53]:
param_grids = [
    {'svm__kernel': ['linear'], 'svm__C': [0.1, 1, 10,100]},
    {'svm__kernel': ['poly'], 'svm__C': [0.1, 1, 10],'svm__gamma':  ['auto','scale', 0.01,0.001], 'svm__degree': [2, 3,4]},
    {'svm__kernel': ['rbf'], 'svm__C': [0.1, 1, 10,100], 'svm__gamma':  ['auto','scale', 0.001,0.01]},
]
    

## Create Stratified 5-Fold Cross-Validation

In [54]:
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('svm',SVC(random_state=42))
])

grid = GridSearchCV(
    estimator=pipe,
    param_grid=param_grids,
    cv=skf,                 # Stratified 5-fold
    scoring='accuracy',    
    n_jobs=-1,              
    verbose=1               
)

## Initialize and Run GridSearchCV on Training Data

In [55]:
grid.fit(X_train_sonar, y_train_sonar)

Fitting 5 folds for each of 56 candidates, totalling 280 fits


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('svm', SVC(random_state=42))]),
             n_jobs=-1,
             param_grid=[{'svm__C': [0.1, 1, 10, 100],
                          'svm__kernel': ['linear']},
                         {'svm__C': [0.1, 1, 10], 'svm__degree': [2, 3, 4],
                          'svm__gamma': ['auto', 'scale', 0.01, 0.001],
                          'svm__kernel': ['poly']},
                         {'svm__C': [0.1, 1, 10, 100],
                          'svm__gamma': ['auto', 'scale', 0.001, 0.01],
                          'svm__kernel': ['rbf']}],
             scoring='accuracy', verbose=1)

## Display Best Parameters and Cross-Validation Score

In [56]:
print("\n Best Parameters:", grid.best_params_)
print(f" Best Cross Validation Score:, {grid.best_score_:.3f}")



 Best Parameters: {'svm__C': 10, 'svm__gamma': 'auto', 'svm__kernel': 'rbf'}
 Best Cross Validation Score:, 0.861


## Evaluate the Best Model on the Test Set

In [57]:
best_model = grid.best_estimator_
new_predictions = best_model.predict(X_test_sonar)

## Display Top 5 Parameter Combinations

In [58]:
results = pd.DataFrame(grid.cv_results_)

cols = ['mean_test_score', 'std_test_score', 'params']
top5 = results.sort_values(by='mean_test_score', ascending=False).head(5)[cols]

print(" Top 5 parameter combinations (by mean CV accuracy):")
print(top5)

 Top 5 parameter combinations (by mean CV accuracy):
    mean_test_score  std_test_score  \
48         0.861497        0.030604   
49         0.861497        0.030604   
53         0.861497        0.030604   
52         0.861497        0.030604   
32         0.850089        0.066305   

                                               params  
48  {'svm__C': 10, 'svm__gamma': 'auto', 'svm__ker...  
49  {'svm__C': 10, 'svm__gamma': 'scale', 'svm__ke...  
53  {'svm__C': 100, 'svm__gamma': 'scale', 'svm__k...  
52  {'svm__C': 100, 'svm__gamma': 'auto', 'svm__ke...  
32  {'svm__C': 10, 'svm__degree': 3, 'svm__gamma':...  


## Display Classification Report for Tuned SVM

In [59]:
print("\nClassification Report:\n", classification_report(y_test_sonar, new_predictions, target_names=["Mine", "Rock"]))


Classification Report:
               precision    recall  f1-score   support

        Mine       0.84      0.95      0.89        22
        Rock       0.94      0.80      0.86        20

    accuracy                           0.88        42
   macro avg       0.89      0.88      0.88        42
weighted avg       0.89      0.88      0.88        42



## Display Confusion Matrix for Tuned SVM

In [60]:
 confusion=confusion_matrix(y_test_sonar,new_predictions)
print(confusion)

[[21  1]
 [ 4 16]]


## Compare Linear SVM vs Tuned SVM Results. Compare experimental results. Explain the performance impact of linear and nonlinear kernels. Why is kernel trick important? Also explain why using k-fold cross validation is more advantageous than train-test split.

In [61]:
'''Our tuned non-linear SVM model outperformed the linear SVM, achieving higher accuracy and better performance across all classification metrics.
This improvement is expected because non-linear kernels are more effective for datasets that are not linearly separable.
While a linear SVM relies on a simple linear decision boundary defined by wx+w0, 
a non-linear kernel implicitly maps the input data into a higher-dimensional feature space, 
enabling the model to learn more complex decision boundaries.
As a result, the kernel function significantly enhanced the model’s ability to distinguish between classes, 
leading to higher overall predictive performance.
Additionally, the use of k-fold cross-validation provided a more reliable estimate of model performance.
Unlike a single train-test split, which divides the dataset randomly once, 
k-fold cross-validation ensures that every data instance is used in both training and testing across multiple iterations.
This approach makes more efficient use of the available data and reduces the variance of the evaluation by averaging results across all folds.'''

'Our tuned non-linear SVM model outperformed the linear SVM, achieving higher accuracy and better performance across all classification metrics.\nThis improvement is expected because non-linear kernels are more effective for datasets that are not linearly separable.\nWhile a linear SVM relies on a simple linear decision boundary defined by wx+w0, \na non-linear kernel implicitly maps the input data into a higher-dimensional feature space, \nenabling the model to learn more complex decision boundaries.\nAs a result, the kernel function significantly enhanced the model’s ability to distinguish between classes, \nleading to higher overall predictive performance.\nAdditionally, the use of k-fold cross-validation provided a more reliable estimate of model performance.\nUnlike a single train-test split, which divides the dataset randomly once, \nk-fold cross-validation ensures that every data instance is used in both training and testing across multiple iterations.\nThis approach makes more 

---
# PART 2: MULTICLASS CLASSIFICATION
---

## Load the Dry Beans Dataset from UCI Repository

In [62]:
from ucimlrepo import fetch_ucirepo
print("Loading Dry Beans dataset...")
dry_bean = fetch_ucirepo(id=602)
X_beans = dry_bean.data.features
X_beans=X_beans.to_numpy()
y_beans = dry_bean.data.targets
y_beans=y_beans.to_numpy()
print(y_beans)

Loading Dry Beans dataset...
[['SEKER']
 ['SEKER']
 ['SEKER']
 ...
 ['DERMASON']
 ['DERMASON']
 ['DERMASON']]


## Encode the Target Labels using LabelEncoder

In [63]:
le = LabelEncoder()
y_beans2 = le.fit_transform(y_beans)
print(y_beans2)
print(len(le.classes_))
''' 0-->BARBUNYA
    1-->BOMBAY
    2-->CALI
    3-->DERMASON
    4-->HOROZ
    5-->SEKER
    6-->SIRA'''

[5 5 5 ... 3 3 3]
7


' 0-->BARBUNYA\n    1-->BOMBAY\n    2-->CALI\n    3-->DERMASON\n    4-->HOROZ\n    5-->SEKER\n    6-->SIRA'

## Split the Data into 80% Training and 20% Testing Sets

In [64]:
X_train_beans, X_test_beans, y_train_beans, y_test_beans = train_test_split(X_beans, y_beans2, train_size=0.8, test_size=0.2,random_state=42)

## Scale the Features using StandardScaler

In [65]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train= scaler.fit_transform(X_train_beans)#standard scaling on data 
X_test=scaler.fit_transform(X_test_beans)

---
## 2.1. Multinomial Logistic Regression
---

## Define the Multinomial Logistic Regression Class

In [66]:
import numpy as np

class MultinomialLogisticRegression:
    def __init__(self, learning_rate=0.01, epochs=1000, reg_lambda=0.0):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.reg_lambda = reg_lambda
        self.weights = None
        self.bias = None
        self.classes_ = None

    # Softmax 
    def _softmax(self, z):
        z = z - np.max(z, axis=1, keepdims=True) #for overflow of large numbers
        exp_z = np.exp(z)
        return exp_z / np.sum(exp_z, axis=1, keepdims=True)

    #  Cross-Entropy Loss
    def _cross_entropy(self, y_true, y_pred):
        m = y_true.shape[0]
        loss = -np.sum(y_true * np.log(y_pred + 1e-15)) / m
        reg = (self.reg_lambda / (2 * m)) * np.sum(self.weights ** 2)
        return loss + reg

    #  Fit 
    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.classes_ = np.unique(y)
        n_classes = len(self.classes_)

        # one-hot encoding
        Y = np.zeros((n_samples, n_classes))
        for i, label in enumerate(y):
            Y[i, np.where(self.classes_ == label)[0][0]] = 1

     
        self.weights = np.zeros((n_classes, n_features))
        self.bias = np.zeros((n_classes, 1))

        for epoch in range(self.epochs):
          
            z = np.dot(X, self.weights.T) + self.bias.T
            probs = self._softmax(z)

            # gradient descent algorithmb
            error = probs - Y
            dw = (np.dot(error.T, X) / n_samples) + (self.reg_lambda / n_samples) * self.weights
            db = np.mean(error, axis=0).reshape(n_classes, 1)

            
            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db


    # Predict Probabilities with softmax function
    def predict_proba(self, X):
        z = np.dot(X, self.weights.T) + self.bias.T
        return self._softmax(z)

    # Predict Labels
    def predict(self, X):
        probs = self.predict_proba(X)
        indices = np.argmax(probs, axis=1)
        return self.classes_[indices]

    #  Accuracy Score
    def score(self, X, y):
        y_pred = self.predict(X)
        return np.mean(y_pred == y)

    #  For GridSearchCV Compatibility
    def get_params(self, deep=True):
        return {
            "learning_rate": self.learning_rate,
            "epochs": self.epochs,
            "reg_lambda": self.reg_lambda
        }

    def set_params(self, **params):
        for key, value in params.items():
            setattr(self, key, value)
        return self
            
              
          
       
          

       
        
                
          
          
            
        
    

## Define Hyperparameter Grid for Multinomial Logistic Regression

In [67]:
param_grid = {
    "learning_rate": [0.01, 0.05, 0.1],
    "epochs": [200, 300, 500],
    "reg_lambda": [0.0, 0.01, 0.1]
}

## Run GridSearchCV for Multinomial Logistic Regression

In [68]:
model = MultinomialLogisticRegression()


grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,               
    scoring='accuracy', 
    n_jobs=-1,        
    verbose=2
)


grid.fit(X_train, y_train_beans)

Fitting 5 folds for each of 27 candidates, totalling 135 fits


GridSearchCV(cv=5,
             estimator=<__main__.MultinomialLogisticRegression object at 0x16b78bb60>,
             n_jobs=-1,
             param_grid={'epochs': [200, 300, 500],
                         'learning_rate': [0.01, 0.05, 0.1],
                         'reg_lambda': [0.0, 0.01, 0.1]},
             scoring='accuracy', verbose=2)

## Evaluate Multinomial Logistic Regression on Test Set

In [69]:
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)
test_accuracy = accuracy_score(y_test_beans, y_pred)
print(f" Test Set Accuracy: {test_accuracy:.3f}")

 Test Set Accuracy: 0.921


## Display Classification Report for Multinomial Logistic Regression

In [70]:
print("\nClassification Report:")
print(classification_report(y_test_beans, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.90      0.92       261
           1       1.00      1.00      1.00       117
           2       0.95      0.95      0.95       317
           3       0.88      0.93      0.90       671
           4       0.96      0.96      0.96       408
           5       0.95      0.94      0.94       413
           6       0.87      0.84      0.86       536

    accuracy                           0.92      2723
   macro avg       0.94      0.93      0.93      2723
weighted avg       0.92      0.92      0.92      2723



## Display Confusion Matrix for Multinomial Logistic Regression

In [71]:
confusion= confusion_matrix(y_test_beans,y_pred)
print(confusion)

[[235   0  14   0   2   1   9]
 [  0 117   0   0   0   0   0]
 [  8   0 300   0   4   1   4]
 [  0   0   0 625   0   8  38]
 [  0   0   3   6 393   0   6]
 [  5   0   0  13   0 387   8]
 [  0   0   0  67   9  10 450]]


---
## 2.2. Decision Tree
---

###  Define the Decision Tree model. Use GridSearchCV to find the best hyperparameters. Perform multiclass classification on the Dry Beans dataset. Print best hyperparameters, classification report and confusion matrix. (15 points)

## Define Hyperparameter Grid for Decision Tree

In [72]:
param_grid_dt = {
    "max_depth": [10, 15, 20, 25, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "criterion": ["gini", "entropy"]
}

## Run GridSearchCV for Decision Tree

In [77]:
dt = DecisionTreeClassifier(random_state=42)

grid_dt = GridSearchCV(
    estimator=dt,
    param_grid=param_grid_dt,
    cv=5, #5k fold cross validation
    scoring='accuracy',
    n_jobs=-1,
    verbose=0
)

grid_dt.fit(X_train_beans, y_train_beans)
best_dt = grid_dt.best_estimator_
y_pred_dt=best_dt.predict(X_test_beans)

test_acc = best_dt.score(X_test_beans, y_test_beans)
print(f"Test Accuracy: {test_acc:.3f}")



#TOP 5 CV SCORES
results = pd.DataFrame(grid_dt.cv_results_)

cols = ['mean_test_score', 'std_test_score', 'params']
top5 = results.sort_values(by='mean_test_score', ascending=False).head(5)[cols]

print(" Top 5 parameter combinations (by mean CV accuracy):")
print(top5)

Test Accuracy: 0.908
 Top 5 parameter combinations (by mean CV accuracy):
    mean_test_score  std_test_score  \
8          0.905033        0.002772   
5          0.904482        0.003647   
51         0.904481        0.007132   
52         0.904481        0.007132   
2          0.904114        0.004663   

                                               params  
8   {'criterion': 'gini', 'max_depth': 10, 'min_sa...  
5   {'criterion': 'gini', 'max_depth': 10, 'min_sa...  
51  {'criterion': 'entropy', 'max_depth': 10, 'min...  
52  {'criterion': 'entropy', 'max_depth': 10, 'min...  
2   {'criterion': 'gini', 'max_depth': 10, 'min_sa...  


## Display Classification Report for Decision Tree

In [78]:
print("\nClassification Report:")
print(classification_report(y_test_beans, y_pred_dt))


Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.86      0.89       261
           1       1.00      1.00      1.00       117
           2       0.88      0.95      0.91       317
           3       0.88      0.92      0.90       671
           4       0.96      0.94      0.95       408
           5       0.96      0.92      0.94       413
           6       0.86      0.85      0.85       536

    accuracy                           0.91      2723
   macro avg       0.92      0.92      0.92      2723
weighted avg       0.91      0.91      0.91      2723



## Display Confusion Matrix for Decision Tree

In [79]:
confusion= confusion_matrix(y_test_beans,y_pred_dt)
print(confusion)

[[225   0  25   0   2   1   8]
 [  0 117   0   0   0   0   0]
 [ 12   0 300   0   4   0   1]
 [  0   0   0 614   2   5  50]
 [  0   0  12   5 383   0   8]
 [  3   0   0  22   0 378  10]
 [  3   0   2  57   8  11 455]]


###  Describe how a decision tree builds its decision structure. (5 points)

In [80]:
'''A decision tree builds its structure using a top-down, greedy algorithm. 
Starting from the full dataset, 
it evaluates all features and possible split thresholds to select the split that yields the largest reduction in impurity (measured by Gini or entropy). 
It recursively repeats this process on each resulting subset until a stopping condition is met. 
The final leaf nodes represent class predictions, forming decision regions in the feature space'''

'A decision tree builds its structure using a top-down, greedy algorithm. \nStarting from the full dataset, \nit evaluates all features and possible split thresholds to select the split that yields the largest reduction in impurity (measured by Gini or entropy). \nIt recursively repeats this process on each resulting subset until a stopping condition is met. \nThe final leaf nodes represent class predictions, forming decision regions in the feature space'

---
## 2.3. XGBoost
---

###  Define the XGBoost model. Use GridSearchCV to find the best hyperparameters. Perform multiclass classification on the Dry Beans dataset. Print best hyperparameters, classification report and confusion matrix(10 points)

## Define Hyperparameter Grid for XGBoost

In [81]:
param_grid_xg = {
  "max_depth": [3, 5, 7, 10],
 "learning_rate": [0.01, 0.1, 0.3],
 "n_estimators": [100, 200, 300],
  "subsample": [0.8, 1.0],
  "colsample_bytree": [0.8, 1.0]
}

## Run GridSearchCV for XGBoost

In [ ]:
model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=6,
    eval_metric="mlogloss",
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

grid_xg = GridSearchCV(
    estimator=model,
    param_grid=param_grid_xg,
    cv=5, #5k fold cross validation
    scoring='accuracy',
    n_jobs=-1,
    verbose=0
)
grid_xg.fit(X_train_beans,y_train_beans)




## Evaluate XGBoost on Test Set

In [254]:
y_pred_xg = model.predict(X_test_beans)
print("Accuracy:", accuracy_score(y_test_beans, y_pred_xg))
#TOP 5 CV SCORES
results = pd.DataFrame(grid_xg.cv_results_)

cols = ['mean_test_score', 'std_test_score', 'params']
top5 = results.sort_values(by='mean_test_score', ascending=False).head(5)[cols]

print(" Top 5 parameter combinations (by mean CV accuracy):")
print(top5)

Accuracy: 0.927653323540213


AttributeError: 'GridSearchCV' object has no attribute 'cv_results_'

## Display Classification Report for XGBoost

In [206]:
print("\nClassification Report:")
print(classification_report(y_test_beans, y_pred_xg))


Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       261
           1       1.00      1.00      1.00       117
           2       0.94      0.95      0.95       317
           3       0.90      0.91      0.91       671
           4       0.98      0.96      0.97       408
           5       0.97      0.94      0.95       413
           6       0.87      0.89      0.88       536

    accuracy                           0.93      2723
   macro avg       0.94      0.94      0.94      2723
weighted avg       0.93      0.93      0.93      2723



## Display Confusion Matrix for XGBoost

In [207]:
confusion= confusion_matrix(y_test_beans,y_pred_xg)
print(confusion)

[[242   0  14   0   0   1   4]
 [  0 117   0   0   0   0   0]
 [  9   0 302   0   4   1   1]
 [  0   0   0 610   1   6  54]
 [  2   0   4   3 392   0   7]
 [  6   0   0  12   0 388   7]
 [  0   0   1  51   5   4 475]]


### What are the revolutionary features of XGBoost compared to other tree-based models?

In [209]:
'''It uses gradient boosting algorithm's optimized version which takes
second order derivative.Also this provides us a faster convergence. 
A lot of trees have the problem of overfitting but XGBoost tries to reduce it by
using L1 and L2 regularization.In addition it includes system level optimizations like
Cache-aware memory access,block based histogram algorithm etc.It has custom loss functions and handles
missing values by chooding automatically the best direction.'''


"It uses gradient boosting algorithm's optimized version which takes\nsecond order derivative.Also this provides us a faster convergence. \nA lot of trees have the problem of overfitting but XGBoost tries to reduce it by\nusing L1 and L2 regularization.In addition it includes system level optimizations like\nCache-aware memory access,block based histogram algorithm etc.It has custom loss functions and handles\nmissing values by chooding automatically the best direction."

###  Compare the classification results of your Multinomial Logistic Regression, Decision Tree, and XGBoost models on the Dry Beans dataset. Discuss the comparison in terms of overall model performance, risk of overfitting, model complexity and the scenarios in which each model is most effective.

''' XGBoost best choice when:
Dataset is large and high-dimensional
Class boundaries are complex and non-linear,
highest accuracy is required,
overfitting and underfitting must be controlled,
competition-level performance is needed'''

'''Multinomial Logistic Regression is best choice when:
Data is moderately sized,
classes are linearly separable or nearly so,
you need a fast, efficient baseline,
interpretability matters'''

'''Decision Tree is best choice when:
you need a very interpretable model,
training time must be minimal,
you want to understand feature splits,
as a first exploratory model—not the final one'''




In [210]:
'''XGBoost achieved the best classification performance on the Dry Beans dataset due to its ability to model complex,
non-linear decision boundaries while controlling overfitting through regularization and boosting. 
Multinomial Logistic Regression provided solid accuracy with low overfitting risk but was limited by its linear decision structure. The Decision Tree model was the most interpretable but showed the lowest generalization performance and the highest tendency to overfit. 
Therefore, XGBoost is the most effective model for this dataset, 
followed by Logistic Regression, and then the Decision Tree.'''

'XGBoost achieved the best classification performance on the Dry Beans dataset due to its ability to model complex,\nnon-linear decision boundaries while controlling overfitting through regularization and boosting. \nMultinomial Logistic Regression provided solid accuracy with low overfitting risk but was limited by its linear decision structure. The Decision Tree model was the most interpretable but showed the lowest generalization performance and the highest tendency to overfit. \nTherefore, XGBoost is the most effective model for this dataset, \nfollowed by Logistic Regression, and then the Decision Tree.'